[font]
size = 14
[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[window]
dynamic_padding = true
opacity = 0.6 # hyprland further reduced opacity

[window.padding]
x = 6
y = 6

[colors.primary]
background = "0x000000"
foreground = "0xffffff"
