background {
    monitor =
    path = ~/Pictures/wallpapers/lockscreen
    blur_passes = 0
}

# Clock
label {
  monitor =
  text = cmd[update:1000] date +"%H:%M"
  font_size = 72
  color = rgb(255, 255, 255)
  position = 0, 300
  halign = center
  valign = center
  font_family = JetBrainsMono Nerd Font Mono
}

# fortune message
label {
  monitor =
  text = cmd[update:20000] fortune -sn 40 | tr -d "\t" | tr '\n' ' '
  position = 0, -500
}

# Password prompt
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 1
    dots_center = true
    fade_on_empty = true
    font_color = rgb(255, 255, 255)
    inner_color = rgb(0, 0, 0)
    outer_color = rgb(255, 255, 255)
    # check_color = rgb(50, 200, 50)
    fail_color = rgb(200, 50, 50)
    placeholder_text =
    font_family = JetBrainsMono Nerd Font Mono
}
