#!/bin/sh
dir="$HOME/Pictures/wallpapers"
selected=$(find "$dir" -type f -printf "%f\n" | rofi -dmenu -p "Select wallpaper")
if [ -n "$selected" ]; then
    awww img "$dir/$selected" --transition-type fade --transition-duration 1
fi

